project:
  type: website
  output-dir: docs
pagetitle: "CV"
website:
  repo-url: https://github.com/SemilleroCI/semillero
  repo-actions: [edit, issue]
  title: "Computer Vision"


  page-footer:
    left: |
      Desarrollado por estudiantes :)
      
    center:
      - text: "Github"
        href: https://github.com/semilleroCV
      - text: "Instagram"
        href: https://www.instagram.com/handsoncv/


    right:  © 2024 Hands-on Computer Vision. Todos los derechos reservados. 
  


  sidebar:
    style: "floating"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


metadata-files:
  - navbar.yml
  - sidebar.yml

